### PR TITLE
Update Phrasing + typos & finalize fr translation of the business section

### PR DESCRIPTION
**Pull request by ObjectifMoon21**
Phrasing + typos + finishing the French translation of business pages

### CODE REVIEW

**Comment by sovenor** [comment]
@ObjectifMoon21 I am resolving some conflicts in these files (not your fault, not sure why it's showing that way).

Anyway, which of these lines is the most up-to-date text? The text on the bottom or top?

"gold_intro_2": "Le bitcoin est une monnaie numérique créée en 2009 et est également considéré par beaucoup comme une valeur refuge.",
	"gold_intro_3": "Mais en quoi un métal physique comme l'or est-il différent d'une monnaie numérique comme le Bitcoin ? Voyons les différences entre ces deux types d'argent : Le bitcoin et l'or.",
=======
	"gold_intro_2": "Le bitcoin est une monnaie numérique créée en 2009 et est également considéré par beaucoup comme une valeur refuge financière.",
	"gold_intro_3": "Mais en quoi un métal physique comme l'or diffère-t-il d'une monnaie numérique comme le bitcoin ? Examinons les différences entre ces deux formes d'argent : Bitcoin et l'or.",

**Comment by sovenor** [comment]
I'm not exactly sure what caused the conflict either. Have you been pulling new commits from the main repo to your forked branch? If not, that may be the source of the issue but I'm not 100% sure.

It's no worries, it should be pretty quick for me to resolve the conflicts now that I know which content is the most up to date. I am running out of time today but will get it sorted ASAP. This PR is next on my list. Thanks!

**Comment by ObjectifMoon21** [comment]
When i finished translating or editing pages, I've pull new commits to my fork via github desktop, then i create the PR the same way as before.

**Comment by sovenor** [comment]
Gotcha, that's the right way as far as I know so you are doing everything correctly.

**Comment by sovenor** [comment]
This has been merged and pushed to the live website. You may need to clear your cache to see the changes. Thanks for your work on this!

**Pull request merged**
