### PR TITLE
First batch of Portuguese Translations

### PR DESCRIPTION
**Pull request by OsodracPT**
Finished translating the following pages: `404_pt`,`bank-runs_pt`,`bitcoin-vs-cbdc_pt`, `bitcoin-vs-gold_pt`,`common_pt`,`compound-inflation-calculator_pt`,`get-involved_pt`, `index_pt`.

### CODE REVIEW

**Comment by sovenor** [comment]
Thanks for this! I will review this next week at the latest.

**Comment by OsodracPT** [comment]
Fixed metadata and finished translating the business section

**Comment by sovenor** [comment]
This has been merged. Thank you so much for your work on this!

I am working on the required manual code to enable Portuguese translations now.

**Comment by sovenor** [comment]
Portuguese translations are now live on the website. You may need to clear your cache to see it as an available option. 

If a first-time user visits the website and their browser language is set to Portuguese, it should automatically display all of the content in Portuguese.

Please let me know if you find any bugs, and thank you again for your work @OsodracPT!

**Pull request merged**
