### PR TITLE
Dutch translation

### PR DESCRIPTION
**Pull request by Binsky21**
I believe I just finished the Dutch translation with the exception of the Sticker files.

Please let me know if there are any mistakes or whatever, give some feedback if possible too.

### CODE REVIEW

**Comment by sovenor** [comment]
Thank you so much for your work on this! I should be finished with the review this week.

**Comment by Binsky21** [comment]
> Thank you so much for your work on this! I should be finished with the review this week.

Thanks! I still need to finish the sticker pages of all languages tho. And they told me to maybe add some kind of note to make it clear that it's mainly for US citizens.

Apart from that, I hope everything is okay :)

**Review by sovenor — APPROVED** [review]
Thank you so much for your work on this! I will work on adding this to the live website now. There are only 2 remaining pages that need to be translated:

- bitcoin-vs-cbdc_nl.json
- sticker-files/dutch/index_nl.json

There's no need to translate the other sticker file pages for the other languages since a Dutch user is likely to only view the sticker files in Dutch.

Before you begin working on those last 2 pages, just be sure to pull the commits I make today so you are on the latest version of all the files.

Thank you!

**Comment by Binsky21** [comment]
Okay @sovenor 

Best wishes for 2025, I've corrected some (hopefully all) typo's I made in the first version of the translation. Also translated those last two pages, do I upload everything again now?

Kind regards, Binsky

**Pull request merged**
